[package]
name = "schulzeug"
version = "0.1.0"
compiler = "0.11.0"
entrypoint = "schulzeug.typ"
authors = ["Jomaway <https://github.com/jomaway>"]
license = "MIT"
description = "A collection of tools to make a teachers life easier (german)." 
repository = ""
keywords = "schulzeug, assignments, exam, template, techer tools"
categories = []
exclude = ["examples/*",]